### ISSUE TITLE
More examples of training

### ISSUE THREAD

**Issue by Ttimofeyka** [cheind/mingru#1]
Hi. I liked your work. I think it's wise to add, for example, training a small model on Shakespeare's dataset or TinyStories?

**Comment by cheind** [comment]
@Ttimofeyka yes I agree. I was actually looking for mini-datasets that could even serve as additional unit-tests. I don't know both of these datasets, but can have a look. Do you have any further references of what to train on those?

**Comment by Ttimofeyka** [comment]
> @Ttimofeyka yes I agree. I was actually looking for mini-datasets that could even serve as additional unit-tests. I don't know both of these datasets, but can have a look. Do you have any further references of what to train on those?

Sure.
https://huggingface.co/datasets/flpelerin/tinystories-100k (as the smallest example)
https://huggingface.co/datasets/JeanKaddour/minipile (good choice for GPT-2 equivalent)
https://huggingface.co/datasets/cchoi1022/openwebtext_20 (as many implementations of GPT-2)

Try to check https://github.com/karpathy/nanoGPT.

**Comment by cheind** [comment]
Thanks, I did start developing a NLP model demo using stacked barebone stacked mingrus  here: https://github.com/cheind/mingru/blob/nlp-gpt-like-demo/mini_nlp.py 
For tiny Shakespeare, this starts producing satisfactory texts (as far as I can tell) after 1 epoch, when trained from scratch with tokenizer based on gpt2.

**Comment by Ttimofeyka** [comment]
> Thanks, I did start developing a NLP model demo using stacked barebone stacked mingrus here: https://github.com/cheind/mingru/blob/nlp-gpt-like-demo/mini_nlp.py For tiny Shakespeare, this starts producing satisfactory texts (as far as I can tell) after 1 epoch, when trained from scratch with tokenizer based on gpt2.

Good! Try to put the most difficult part of the code in a separate file inside a mingru folder, 'cause code seems a bit of crap now (all things messed).

Also try to check https://github.com/KellerJordan/modded-nanogpt - this is a more fast version of NanoGPT project, may be useful.

**Comment by cheind** [comment]
Thanks your suggestions. Text generation uses a barbone stacked MinGRU using GTP-2 vocab-size, I'm not planning to extend this demo any further.
